class SiteTemplate < Template
  #HTML = ""
  def initialize *o
    super
    use_style SiteStyle.new(document)
    build(document.getElementsByTagName('head')[0]) do
      meta("http-equiv"=>"content-type","content"=>"text/html; charset=utf-8") do
      end

      meta("name"=>"description","content"=>"your description goes here") do
      end

      meta("name"=>"keywords","content"=>"your,keywords,goes,here") do
      end

      meta("name"=>"author","content"=>"Your Name  / Original design: Andreas Viklund - http://andreasviklund.com/") do
      end

      meta("name"=>"generator","content"=>"webgen - http://webgen.rubyforge.org") do
      end
    end

    build() do
      div("id"=>"thetop") do

        a("id"=>"top") do
        end

        p("class"=>"hide") do
          text "Skip to: "

          a("href"=>"#sitemenu","accesskey"=>"2") do
            text "Site menu"
          end
          text " | "

          a("href"=>"#maincontent","accesskey"=>"3") do
            text "Main content"
          end
        end
      end

      div("id"=>"container") do

        div("id"=>"main") do

          div("id"=>"logo") do

            h1() do
              text "["

              a("href"=>"index.html","accesskey"=>"4",'id'=>"logo_link","class"=>"page_data") do
                text "your site title"
              end
              text "]"
            end

            span("id"=>"tagline","class"=>"page_data") do
              text "Your striking site slogan!"
            end
          end

          div("id"=>"intro") do

            h3("class"=>"page_data","id"=>"overview_header") do

              a("id"=>"maincontent") do
              end
              text "Website description!"
            end

            p("class"=>"page_data","id"=>"overview") do
              text "Here could go a description of your website! Or a quick overview of the page!"
            end
          end

          div("class"=>"clear") do
          end

          h2("id"=>"content_header",'class'=>'page_data') do
            text "Welcome to "

            em() do
              text "webgen"
            end
            text "!"
          end
         
          div('id'=>'content','class'=>'page_data') do
            p() do
              text "This is just a place holder for the start page for your new website!"
            end

            p() do
              text "You can start by adjusting the meta information for this page file and adding some real content and
      then adding some more page files!"
            end

            p() do
              text "For more information about webgen have a look at the "

              a("href"=>"http://webgen.rubyforge.org/documentation/index.html") do
                text "documentation"
              end
              text "!"
            end
          end
        end

        div("id"=>"sidebar") do

          h2("class"=>"sidelink menuheader") do

            a("id"=>"sitemenu") do
            end
            text "Menu:"
          end

          div("id"=>"menu") do

            ul('class'=>'page_data','id'=>'nav_bar') do

              li("class"=>"webgen-menu-level1 webgen-menu-item-selected") do

                span() do
                  text "Empty Index Page"
                end
              end
            end
          end

          a("class"=>"hide","href"=>"#top","accesskey"=>"1") do
            text "Top of page"
          end
          br();br()
          h3() do
            text "Related links"
          end

          ul("class"=>"linklist page_data","id"=>'related') do

            li() do

              a("href"=>"http://andreasviklund.com/templates") do
                text "Free website templates"
              end
            end

            li() do

              a("href"=>"http://openwebdesign.org") do
                text "Open Web Design"
              end
            end

            li() do

              a("href"=>"http://oswd.org") do
                text "OSWD.org"
              end
            end

            li() do

              a("href"=>"http://andreasviklund.com/music/lagoona") do
                text "Lagoona MP3s"
              end
            end
          end
        end

        div("class"=>"clear") do
        end
      end

      div("id"=>"footer") do

        p() do
          text "(c) 2012 ppibburr | Generated by"

          a("href"=>"http://ppibburr.github.com/ruby_js") do
            text "RubyJS"
          end
          text " | Design by "

          a("href"=>"http://andreasviklund.com") do
            text "Andreas Viklund"
          end
        end
      end
    end
  end
end
